CREATE DATABASE IF NOT EXISTS exp192;
CREATE USER IF NOT EXISTS 'exp192_user' @'localhost' identified BY 'acml2016';
GRANT DELETE,INSERT,SELECT,UPDATE ON  exp192.* TO 'exp192_user' @'localhost';
FLUSH privileges;
USE exp192;
-- 上書き用
DROP TABLE IF EXISTS pairs;
DROP TABLE IF EXISTS players;
-- プレイヤー情報の管理用テーブル
CREATE TABLE IF NOT EXISTS players(
    -- id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    -- user_id VARCHAR(20) NOT NULL UNIQUE,
    id VARCHAR(20) PRIMARY KEY,
    is_host BOOLEAN DEFAULT NULL,
    is_male BOOLEAN DEFAULT NULL,
    age TINYINT UNSIGNED DEFAULT 255,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) engine = innodb DEFAULT charset = utf8 COLLATE = utf8_unicode_ci AUTO_INCREMENT = 1;
-- ペア情報の管理用テーブル
CREATE TABLE IF NOT EXISTS pairs(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    host_id VARCHAR(20) DEFAULT NULL,
    guest_id VARCHAR(20) DEFAULT NULL,
    phase VARCHAR(10) DEFAULT NULL, 
    status VARCHAR(10) DEFAULT "DEFAULT", 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_host_id FOREIGN KEY(host_id) REFERENCES players(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_guest_id FOREIGN KEY(guest_id) REFERENCES players(id) ON DELETE RESTRICT ON UPDATE CASCADE
) engine = innodb DEFAULT charset = utf8 COLLATE = utf8_unicode_ci AUTO_INCREMENT = 1;

-- 各ペアの各ラウンドの位置情報の管理用テーブル
CREATE TABLE IF NOT EXISTS positions(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pair_id INT UNSIGNED NOT NULL, 
    current_round INT UNSIGNED NOT NULL,
    reward_position TINYINT UNSIGNED, 
    host_position TINYINT UNSIGNED, 
    guest_position TINYINT UNSIGNED, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pair_id FOREIGN KEY(pair_id) REFERENCES pairs(id) ON DELETE RESTRICT ON UPDATE CASCADE
) engine = innodb DEFAULT charset = utf8 COLLATE = utf8_unicode_ci AUTO_INCREMENT = 1;