CREATE DATABASE IF NOT EXISTS exp192;
CREATE USER IF NOT EXISTS 'exp192_user'@'localhost' IDENTIFIED BY 'acml2016';
GRANT DELETE, INSERT, SELECT, UPDATE ON exp192.* TO 'exp192_user'@'localhost';
FLUSH PRIVILEGES;
USE exp192;

/* 上書き用 */
DROP TABLE IF EXISTS pairs;
DROP TABLE IF EXISTS players;

/* プレイヤー情報の管理用テーブル */
CREATE TABLE IF NOT EXISTS players
(
    id INT UNSIGNED AUTO_INCREMENT,
    socket_id VARCHAR(20) NOT NULL UNIQUE,
    sex INT DEFAULT 0, -- 1=male,2=female
    age INT DEFAULT 999,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
)
ENGINE = InnoDB 
DEFAULT CHARSET = utf8 
COLLATE = utf8_unicode_ci
AUTO_INCREMENT = 1 ;

/* ペア情報の管理用テーブル */
CREATE TABLE IF NOT EXISTS pairs
(
    id INT UNSIGNED AUTO_INCREMENT,
    host_id INT UNSIGNED DEFAULT NULL,
    guest_id INT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_host_id
        FOREIGN KEY(host_id) 
        REFERENCES players(id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    CONSTRAINT fk_guest_id
        FOREIGN KEY(guest_id) 
        REFERENCES players(id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,
    PRIMARY KEY(id)
)
ENGINE = InnoDB 
DEFAULT CHARSET = utf8 
COLLATE = utf8_unicode_ci
AUTO_INCREMENT = 1 ;
